version: "3.9"

services:
  netpulse-service:
    build:
      context: .
      dockerfile: ./Containerfile
    container_name: netpulse-container
    ports:
      - "9930:9930"
      - "9333:9333"
      - "9944:9944"
      - "30333:30333"
      - "30334:30334"
    volumes:
      - data:/data
    environment:
      - RUST_BACKTRACE=1
    command: ["/usr/bin/Netpulse"]

volumes:
  data:
    driver: local
