apiVersion: apps/v1
kind: default
metadata:
  name: netpulse-blockchain
  labels:
    app: netpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      labels:
        app: netpulse
    spec:
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse:latest # Replace with your image path
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources: # Recommended: Add resource requests and limits
          requests:
            cpu: 100m # 0.1 CPU
            memory: 256Mi
          limits:
            cpu: 500m # 0.5 CPU
            memory: 512Mi