spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      labels:
        app: netpulse
    spec:
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse:latest
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"