apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpulse-blockchain
  namespace: default
  labels:
    app: netpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      labels:
        app: netpulse
    spec:
      # Uncomment and set the correct service account if needed
      # serviceAccountName: 115873905373554535626
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 500m
            memory: 2Gi
      imagePullSecrets:
      - name: gcr-key
