apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpulse-blockchain
  namespace: default
  labels:
    app: netpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      labels:
        app: netpulse
    spec:
      serviceAccountName: 06829c2d76387618dd7de5a51b32ffc407f62248
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse:latest
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 500m
            memory: 2Gi