apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpulse-blockchain
  namespace: default
  labels:
    app: netpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      labels:
        app: netpulse
    spec:
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse@sha256:af6483f8ac1897686172c2e6b4058bee475e0c10e78c68fc7976e2acc690024e
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi