apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpulse-blockchain
  namespace: default # Replace with your desired namespace
  labels:
    app: netpulse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netpulse
  template:
    metadata:
      namespace: default # Important: Match the Deployment's namespace
      labels:
        app: netpulse
    spec:
      containers:
      - name: netpulse
        image: gcr.io/airy-coil-394706/netpulse:latest # Replace with your actual image path
        ports:
        - containerPort: 9930
        - containerPort: 9333
        - containerPort: 9944
        - containerPort: 30333
        - containerPort: 30334
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi