name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Set up gcloud CLI
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: gke-gcloud-auth-plugin

    # Authenticate Docker to push images to Google Container Registry (if needed)
    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker gcr.io

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}
        kubectl apply -f k8s/deployment.yaml

    # Verify deployment
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/netpulse-blockchain
        kubectl get pods
