name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate with Google Cloud
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > "${{ runner.temp }}/gcloud-key.json"
        gcloud auth activate-service-account --key-file="${{ runner.temp }}/gcloud-key.json"
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker gcr.io
    # - name: Build Docker image
    #   run: |
    #     docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/netpulse:latest -f Containerfile .

    # - name: Push Docker image
    #   run: |
    #     docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/netpulse:latest

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}
        kubectl apply -f k8s/deployment.yaml

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/netpulse-blockchain -n default
        kubectl get pods -n default
