# name: Deploy to GKE

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy: # Job name
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Google Cloud SDK
#       uses: google-github-actions/setup-gcloud@v2
#       with:
#         version: 'latest'
#         project_id: ${{ secrets.GCP_PROJECT_ID }}

#     - name: Install GKE auth plugin
#       run: |
#         gcloud components install gke-gcloud-auth-plugin
#         gcloud components update

#     - name: Authenticate Docker with Google Cloud
#       env:
#         GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
#       run: |
#         echo "$GCP_SA_KEY" > ${HOME}/gcloud-service-key.json
#         gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
#         gcloud auth configure-docker gcr.io --quiet

#     # - name: Build Docker image
#     #   run: |
#     #     IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/netpulse:latest
#     #     docker build -t $IMAGE -f Containerfile .

#     # - name: Push Docker image
#     #   run: |
#     #     IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/netpulse:latest
#     #     docker push $IMAGE

#     - name: Deploy to GKE
#       run: |
#         gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
#           --zone ${{ secrets.GKE_CLUSTER_ZONE }} \
#           --project ${{ secrets.GCP_PROJECT_ID }}
#         kubectl apply -f k8s/deployment.yaml

#     - name: Verify Deployment
#       run: |
#         kubectl rollout status deployment/netpulse-blockchain -n default
#         kubectl get pods -n default # Optional: View pods
